name: proyecto
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  particles_flutter: ^1.0.1
  image_picker: ^1.1.2
  firebase_core: ^3.8.1 
  firebase_database:  ^11.2.0 
  cloud_firestore: ^5.5.1
  firebase_storage:  ^12.3.7
  firebase_core_web: ^2.18.2 
  firebase_auth: ^5.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Sección para los assets
  assets:
    - assets/flores.jpg # Imagen utilizada en el Drawer
    - assets/illustration_dogs.jpg
    - assets/illustration_login.jpg
    - assets/illustration_signup.jpg
    - assets/fondo_huellitas.jpg
    - assets/comida_hipoalergenica.jpg # Nueva imagen para la comida hipoalergénica
    - assets/cuidado_dientes.jpg # Nueva imagen para cuidado de dientes
    - assets/ejercicio_perro.jpg # Nueva imagen para ejercicio de perro
    - assets/vacunacion_perro.jpg # Nueva imagen para vacunación
    - assets/bano_perro.jpg # Nueva imagen para baño de perro
    - assets/perrito.jpg
    - assets/fondo_familia.jpg
    - assets/salchicha.jpg
    - assets/perrito_feliz.jpg